import { prisma } from "@/lib/db";
import { auditLog } from "@/lib/services/audit";

/**
 * SEO Service
 * ===========
 *
 * Manages global SEO configuration backed by SystemSetting rows.
 * Reuses the existing app/robots.ts and app/sitemap.ts routes —
 * this service just provides the configurable metadata they read
 * from, plus a technical audit of SEO posture.
 */

// ─── Robots.txt builder ──────────────────────────────────────────

export function buildRobotsTxt(canonicalBase: string, indexPrivateRoutes: boolean): string {
  // Always disallow private paths from indexing — even if the admin
  // toggles "indexPrivateRoutes" on, we keep /admin, /api, etc. blocked.
  // The toggle only controls whether /login, /register are indexed.
  const alwaysBlocked = ["/admin", "/admin/*", "/employee", "/employee/*", "/student", "/student/*", "/api", "/api/*"];
  const conditionalBlocked = indexPrivateRoutes ? [] : ["/login", "/register"];

  const rules: Array<{ userAgent: string; allow: string[]; disallow: string[] }> = [
    {
      userAgent: "*",
      allow: ["/"],
      disallow: [...alwaysBlocked, ...conditionalBlocked],
    },
  ];

  let output = "";
  for (const rule of rules) {
    output += `User-agent: ${rule.userAgent}\n`;
    for (const a of rule.allow) output += `Allow: ${a}\n`;
    for (const d of rule.disallow) output += `Disallow: ${d}\n`;
    output += "\n";
  }
  output += `Sitemap: ${canonicalBase}/sitemap.xml\n`;
  output += `Host: ${canonicalBase.replace(/^https?:\/\//, "")}\n`;
  return output;
}

// ─── Sitemap inputs ──────────────────────────────────────────────

export async function getSitemapUniversities() {
  try {
    return await prisma.university.findMany({
      where: { deletedAt: null },
      select: { slug: true, updatedAt: true },
    });
  } catch {
    return [];
  }
}

export async function getSitemapCourses() {
  try {
    return await prisma.course.findMany({
      where: { deletedAt: null },
      select: { slug: true, updatedAt: true },
    });
  } catch {
    return [];
  }
}

// ─── SEO technical audit ─────────────────────────────────────────

export type SeoFinding = {
  check: string;
  status: "PASS" | "WARN" | "FAIL";
  detail: string;
  recommendation?: string;
};

export async function auditSeo(): Promise<{
  findings: SeoFinding[];
  summary: { pass: number; warn: number; fail: number };
}> {
  const findings: SeoFinding[] = [];

  const seoConfig = await import("./config").then((m) => m.getSeoConfig());

  // Title
  findings.push({
    check: "Site name configured",
    status: seoConfig.siteName ? "PASS" : "FAIL",
    detail: seoConfig.siteName || "Empty",
  });

  // Meta description
  findings.push({
    check: "Meta description configured",
    status: seoConfig.metaDescription.length > 50 ? "PASS" : seoConfig.metaDescription.length > 0 ? "WARN" : "FAIL",
    detail: `${seoConfig.metaDescription.length} chars (recommended ≥120)`,
    recommendation: "Set a meta description of at least 120 characters",
  });

  // Canonical
  findings.push({
    check: "Canonical base URL",
    status: seoConfig.canonicalBase.startsWith("https://") ? "PASS" : "FAIL",
    detail: seoConfig.canonicalBase,
    recommendation: "Use https:// URL in production",
  });

  // robots.txt
  findings.push({
    check: "robots.txt route",
    status: "PASS",
    detail: "Auto-generated by app/robots.ts",
  });

  // sitemap.xml
  const uniCount = await getSitemapUniversities().then((r) => r.length);
  const courseCount = await getSitemapCourses().then((r) => r.length);
  findings.push({
    check: "sitemap.xml route",
    status: "PASS",
    detail: `Auto-generated by app/sitemap.ts (${uniCount} universities, ${courseCount} courses)`,
  });

  // HTTPS
  findings.push({
    check: "HTTPS canonical URL",
    status: seoConfig.canonicalBase.startsWith("https://") ? "PASS" : "FAIL",
    detail: seoConfig.canonicalBase,
    recommendation: "Use https:// in production",
  });

  // Private route protection
  findings.push({
    check: "Private routes blocked (noindex via robots.txt)",
    status: "PASS",
    detail: `/admin, /employee, /student, /api always blocked`,
  });

  // OpenGraph
  findings.push({
    check: "Default OpenGraph image",
    status: seoConfig.defaultOgImage ? "PASS" : "WARN",
    detail: seoConfig.defaultOgImage || "Not set",
    recommendation: "Set a 1200×630 image for OG previews",
  });

  // Twitter
  findings.push({
    check: "Default Twitter card image",
    status: seoConfig.defaultTwitterImage ? "PASS" : "WARN",
    detail: seoConfig.defaultTwitterImage || "Not set",
  });

  // Locale
  findings.push({
    check: "Locale configured",
    status: seoConfig.locale ? "PASS" : "WARN",
    detail: seoConfig.locale,
  });

  // Structured data
  findings.push({
    check: "Organization structured data (JSON-LD)",
    status: "PASS",
    detail: "EducationalOrganization schema in app/layout.tsx",
  });

  // App URL matches canonical
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "";
  findings.push({
    check: "NEXT_PUBLIC_APP_URL matches canonical base",
    status: appUrl === seoConfig.canonicalBase ? "PASS" : "WARN",
    detail: `app_url=${appUrl}, canonical=${seoConfig.canonicalBase}`,
    recommendation: "Keep these aligned to avoid duplicate-content penalties",
  });

  const summary = {
    pass: findings.filter((f) => f.status === "PASS").length,
    warn: findings.filter((f) => f.status === "WARN").length,
    fail: findings.filter((f) => f.status === "FAIL").length,
  };

  return { findings, summary };
}

// ─── Persist SEO config (admin write) ─────────────────────────────

export async function updateSeoConfig(
  updates: Record<string, unknown>,
  actorId: string,
  ctx?: { ipAddress?: string; userAgent?: string },
): Promise<void> {
  const { setConfig } = await import("./config");
  for (const [key, value] of Object.entries(updates)) {
    if (key.startsWith("seo.")) {
      await setConfig(key, value, actorId);
    }
  }
  await auditLog.record({
    userId: actorId,
    action: "seo_setting.updated",
    entity: "SystemSetting",
    entityId: "seo",
    newValue: updates,
    ipAddress: ctx?.ipAddress,
    userAgent: ctx?.userAgent,
  });
}
