"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiFetch } from "@/lib/api-client";
import { PageHeader, LoadingState } from "@/components/shared/page-kit";
import { Button, Input, Label, Textarea, Select } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { SectionCard, StatusBadge } from "./shared";
import { Save, Search, FileText, Globe } from "lucide-react";

type SeoConfig = {
  siteName: string;
  titleTemplate: string;
  metaDescription: string;
  locale: string;
  language: string;
  defaultOgImage: string;
  defaultTwitterImage: string;
  canonicalBase: string;
  indexPrivateRoutes: boolean;
};

type SeoFinding = {
  check: string;
  status: "PASS" | "WARN" | "FAIL";
  detail: string;
  recommendation?: string;
};

type SeoResponse = {
  config: SeoConfig;
  audit: { findings: SeoFinding[]; summary: { pass: number; warn: number; fail: number } };
};

export function SeoManager() {
  const { data, isPending } = useQuery({
    queryKey: ["/api/admin/system/seo"],
    queryFn: () => apiFetch<SeoResponse>("/api/admin/system/seo"),
    staleTime: 30 * 1000,
  });

  if (isPending) return <LoadingState label="Loading SEO config…" />;
  if (!data) return <p className="text-destructive">Failed to load SEO config.</p>;

  return (
    <div className="space-y-6">
      <PageHeader
        title="SEO Management"
        description="Global SEO settings, robots.txt, sitemap.xml verification, and technical audit."
        breadcrumbs={["Admin", "System Administration", "SEO"]}
      />

      <SeoConfigForm initial={data.config} />

      <SectionCard
        title="robots.txt"
        description="Auto-generated by app/robots.ts. Private routes (/admin, /employee, /student, /api) are always blocked."
        actions={<FileText className="h-4 w-4 text-muted-foreground" />}
      >
        <pre className="overflow-x-auto rounded-md bg-muted/50 p-3 text-xs font-mono">
{`User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/*
Disallow: /employee
Disallow: /employee/*
Disallow: /student
Disallow: /student/*
Disallow: /api
Disallow: /api/*
${data.config.indexPrivateRoutes ? "" : "Disallow: /login\nDisallow: /register\n"}
Sitemap: ${data.config.canonicalBase}/sitemap.xml
Host: ${data.config.canonicalBase.replace(/^https?:\/\//, "")}`}
        </pre>
      </SectionCard>

      <SectionCard
        title="sitemap.xml"
        description="Auto-generated by app/sitemap.ts. Includes all public marketing pages + dynamic university/course pages."
        actions={<Globe className="h-4 w-4 text-muted-foreground" />}
      >
        <div className="space-y-2 text-sm">
          <p className="text-muted-foreground">
            The sitemap is generated on each request from the live database. Public routes included:
          </p>
          <div className="flex flex-wrap gap-1">
            {["/", "/study-in-europe", "/universities", "/courses", "/features", "/how-it-works", "/about", "/contact", "/login", "/register"].map((p) => (
              <code key={p} className="rounded bg-muted px-1.5 py-0.5 text-xs">{p}</code>
            ))}
            <code className="rounded bg-muted px-1.5 py-0.5 text-xs">/universities/[slug]</code>
            <code className="rounded bg-muted px-1.5 py-0.5 text-xs">/courses/[slug]</code>
          </div>
          <p className="text-xs text-muted-foreground">
            <strong>Excluded by design:</strong> /admin, /employee, /student, /api — private data behind authentication.
          </p>
        </div>
      </SectionCard>

      <SectionCard
        title="Technical SEO Audit"
        description="Automated checks against the current configuration."
        actions={<Search className="h-4 w-4 text-muted-foreground" />}
      >
        <div className="space-y-2">
          {data.audit.findings.map((f) => (
            <div key={f.check} className="flex items-start gap-3 rounded-md border border-border bg-background/50 p-3">
              <StatusBadge status={f.status as "PASS" | "WARN" | "FAIL"} />
              <div className="flex-1">
                <p className="text-sm font-medium">{f.check}</p>
                <p className="text-xs text-muted-foreground">{f.detail}</p>
                {f.recommendation && (
                  <p className="mt-1 text-xs text-warning">→ {f.recommendation}</p>
                )}
              </div>
            </div>
          ))}
        </div>
        <p className="mt-3 text-xs text-muted-foreground">
          Summary: {data.audit.summary.pass} pass, {data.audit.summary.warn} warn, {data.audit.summary.fail} fail
        </p>
      </SectionCard>

      <SectionCard
        title="Structured Data (JSON-LD)"
        description="Schema.org markup emitted by app/layout.tsx"
      >
        <pre className="overflow-x-auto rounded-md bg-muted/50 p-3 text-xs font-mono">
{`{
  "@context": "https://schema.org",
  "@type": "EducationalOrganization",
  "name": "${data.config.siteName}",
  "url": "${data.config.canonicalBase}",
  "description": "${data.config.metaDescription.slice(0, 80)}…",
  "slogan": "${data.config.siteName}",
  "knowsAbout": [
    "European university admissions",
    "Student visa preparation",
    "Study abroad Europe"
  ]
}`}
        </pre>
      </SectionCard>
    </div>
  );
}

function SeoConfigForm({ initial }: { initial: SeoConfig }) {
  const { toast } = useToast();
  const qc = useQueryClient();
  const [form, setForm] = useState<SeoConfig>(initial);

  const mutation = useMutation({
    mutationFn: async () => {
      const updates: Record<string, unknown> = {};
      (Object.keys(form) as (keyof SeoConfig)[]).forEach((k) => {
        if (form[k] !== initial[k]) {
          updates[`seo.${k}`] = form[k];
        }
      });
      if (Object.keys(updates).length === 0) {
        throw new Error("No changes to save");
      }
      return apiFetch("/api/admin/system/seo", { method: "PUT", json: updates });
    },
    onSuccess: () => {
      toast({ title: "SEO config saved", variant: "success" });
      qc.invalidateQueries({ queryKey: ["/api/admin/system/seo"] });
    },
    onError: (err) => toast({ title: "Save failed", description: (err as Error).message, variant: "error" }),
  });

  const set = <K extends keyof SeoConfig>(k: K, v: SeoConfig[K]) =>
    setForm((f) => ({ ...f, [k]: v }));

  return (
    <SectionCard
      title="Site SEO Settings"
      description="Global metadata applied to all public pages."
      actions={
        <Button onClick={() => mutation.mutate()} disabled={mutation.isPending}>
          <Save className="h-4 w-4" /> Save
        </Button>
      }
    >
      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-1">
          <Label>Site Name</Label>
          <Input value={form.siteName} onChange={(e) => set("siteName", e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Title Template</Label>
          <Input value={form.titleTemplate} onChange={(e) => set("titleTemplate", e.target.value)} placeholder="%s | Euroscope" />
        </div>
        <div className="space-y-1 md:col-span-2">
          <Label>Meta Description (recommended ≥120 chars)</Label>
          <Textarea
            value={form.metaDescription}
            onChange={(e) => set("metaDescription", e.target.value)}
            maxLength={500}
            rows={3}
          />
          <p className="text-xs text-muted-foreground">{form.metaDescription.length}/500</p>
        </div>
        <div className="space-y-1">
          <Label>Locale</Label>
          <Input value={form.locale} onChange={(e) => set("locale", e.target.value)} placeholder="en_US" />
        </div>
        <div className="space-y-1">
          <Label>Language</Label>
          <Select value={form.language} onChange={(e) => set("language", e.target.value)}>
            <option value="en">English</option>
            <option value="bn">বাংলা</option>
            <option value="de">Deutsch</option>
            <option value="fr">Français</option>
          </Select>
        </div>
        <div className="space-y-1">
          <Label>Canonical Base URL</Label>
          <Input value={form.canonicalBase} onChange={(e) => set("canonicalBase", e.target.value)} placeholder="https://your-domain.com" />
        </div>
        <div className="space-y-1">
          <Label>Default OpenGraph Image</Label>
          <Input value={form.defaultOgImage} onChange={(e) => set("defaultOgImage", e.target.value)} placeholder="/og-image.png" />
        </div>
        <div className="space-y-1">
          <Label>Default Twitter/X Image</Label>
          <Input value={form.defaultTwitterImage} onChange={(e) => set("defaultTwitterImage", e.target.value)} />
        </div>
        <div className="space-y-1 md:col-span-2">
          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={form.indexPrivateRoutes}
              onChange={(e) => set("indexPrivateRoutes", e.target.checked)}
              className="h-4 w-4"
            />
            <span>Allow indexing of /login and /register (NOT recommended for private apps)</span>
          </label>
          <p className="text-xs text-muted-foreground">
            /admin, /employee, /student, /api are always blocked regardless of this setting.
          </p>
        </div>
      </div>
    </SectionCard>
  );
}
